### ISSUE TITLE
nanobody mode: "Error: local variable 'Hchain' referenced before assignment"

### ISSUE THREAD

**Issue by jdekanter** [oxpig/AntiFold#10]
Hi Magnus, thanks for the great work!
I wanted to try out the package (v0.2.3) on nanobodies using the option you provided, but I get an error message.
To exclude that it is due to renumbering, I tried it on the `data/pdbs/6y1l_imgt.pdb` example data, like so:
`python antifold/main.py --pdb_file data/pdbs/6y1l_imgt.pdb --nanobody_chain H` and I get the same error (see below). From the code my guess would be that something already goes wrong with generating the `pdbs_csv` in `generate_pdbs_csv`, but I am not sure.
Just running `python antifold/main.py --pdb_file data/pdbs/6y1l_imgt.pdb` gives no problems.

Any help would be welcome!

> [2024-07-18 11:09:17,810] Running inverse folding on PDB/CIFs ...
[2024-07-18 11:09:17,810] WARNING: Heavy/light chain(s) not specified for 6y1l_imgt. Assuming 1st chain heavy, 2nd chain light.
[2024-07-18 11:09:17,810] WARNING: Specify manually with e.g. --heavy_chain H --light_chain L
/home/ubuntu/resources/miniconda3/envs/antifold_gpu/lib/python3.10/site-packages/antifold/antiscripts.py:109: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint_dict = torch.load(checkpoint_path, map_location=torch.device(device))
[2024-07-18 11:09:20,315] Loaded model to cuda.
[2024-07-18 11:09:20,317] NOTE: Custom chain mode enabled. Will run all specified chains (not just heavy/light).
[2024-07-18 11:09:20,317] Reading in (1) PDBs from DataFrame
[2024-07-18 11:09:20,318] Prediction encountered an unexpected error: local variable 'Hchain' referenced before assignment
Traceback (most recent call last):
  File "/home/ubuntu/resources/AntiFold/antifold/main.py", line 488, in <module>
    main(args)
  File "/home/ubuntu/resources/AntiFold/antifold/main.py", line 438, in main
    pdb_output_dict = sample_pdbs(
  File "/home/ubuntu/resources/AntiFold/antifold/main.py", line 209, in sample_pdbs
    df_logits_list = get_pdbs_logits(
  File "/home/ubuntu/resources/miniconda3/envs/antifold_gpu/lib/python3.10/site-packages/antifold/antiscripts.py", line 456, in get_pdbs_logits
    dataset, dataloader = get_dataset_dataloader(
  File "/home/ubuntu/resources/miniconda3/envs/antifold_gpu/lib/python3.10/site-packages/antifold/antiscripts.py", line 241, in get_dataset_dataloader
    dataset.populate(pdbs_csv_or_dataframe, pdb_dir)
  File "/home/ubuntu/resources/miniconda3/envs/antifold_gpu/lib/python3.10/site-packages/antifold/if1_dataset.py", line 213, in populate
    "Hchain": Hchain,
UnboundLocalError: local variable 'Hchain' referenced before assignment

**Comment by Magnushhoie** [comment]
Hi J. K. de Kanter and thanks!

The command you ran and the nanobody README example should work without errors on the latest AntiFold version 0.2.3:

```bash
(antifold) mhoie@Magnuss-MBP AntiFold % python antifold/main.py --pdb_file data/pdbs/6y1l_imgt.pdb --nanobody_chain H
[2024-07-20 14:59:31,919] Running inverse folding on PDB/CIFs ...
[2024-07-20 14:59:32,429] Loaded model to cpu.
[2024-07-20 14:59:32,430] NOTE: Custom chain mode enabled. Will run specified chain(s).
[2024-07-20 14:59:32,430] Reading in (1) PDBs from DataFrame
[2024-07-20 14:59:32,448] Predicting batch 1/1: PDBs 1-1 out of 1 total
[2024-07-20 14:59:35,163] Saving 1 CSVs to antifold_output
[2024-07-20 14:59:35,164] Writing 6y1l_imgt_H per-residue log probs CSV to antifold_output/6y1l_imgt_H.csv
```

Could you try cloning the Github repository again and creating a fresh conda environment?

**Comment by jdekanter** [comment]
Hi Magnus,

Thank you for the reply. I tried to install the environment for GPU. I think something went wrong there. I no just followed the "default" installation and everything runs fine. Thank you!

**Comment by Magnushhoie** [comment]
Fantastic, I see now that the Github and pip versions are out of sync, and have updated the package version number to 0.3.0

**Comment by jdekanter** [comment]
Great, thanks for the update!

I am reopening the issue as I now noticed that this code stops working when you add the `--num_seq_per_target` argument:

`(antifold) Antifold: ~/resources/AntiFold$ python antifold/main.py --pdb_file data/pdbs/6y1l_imgt.pdb --nanobody_chain H`

> [2024-07-26 08:50:07,085] Running inverse folding on PDB/CIFs ...
> [2024-07-26 08:50:08,593] Loaded model to cpu.
> [2024-07-26 08:50:08,594] NOTE: Custom chain mode enabled. Will run specified chain(s).
> [2024-07-26 08:50:08,594] Reading in (1) PDBs from DataFrame
> [2024-07-26 08:50:08,634] Predicting batch 1/1: PDBs 1-1 out of 1 total
> [2024-07-26 08:50:10,149] Saving 1 CSVs to antifold_output
> [2024-07-26 08:50:10,151] Writing 6y1l_imgt_H per-residue log probs CSV to antifold_output/6y1l_imgt_H.csv

`(antifold) Antifold: ~/resources/AntiFold$ python antifold/main.py --pdb_file data/pdbs/6y1l_imgt.pdb --nanobody_chain H --num_seq_per_target 10`

> [2024-07-26 08:50:16,113] Running inverse folding on PDB/CIFs ...
> [2024-07-26 08:50:16,114] Will sample 10 sequences from 1 PDBs at temperature(s) [0.2] and regions: ['CDR1', 'CDR2', 'CDR3']
> [2024-07-26 08:50:17,617] Loaded model to cpu.
> [2024-07-26 08:50:17,619] NOTE: Custom chain mode enabled. Will run specified chain(s).
> [2024-07-26 08:50:17,619] Reading in (1) PDBs from DataFrame
> [2024-07-26 08:50:17,659] Predicting batch 1/1: PDBs 1-1 out of 1 total
> [2024-07-26 08:50:19,207] Saving 1 CSVs to antifold_output
> [2024-07-26 08:50:19,210] Writing 6y1l_imgt_H per-residue log probs CSV to antifold_output/6y1l_imgt_H.csv
> [2024-07-26 08:50:19,217] Prediction encountered an unexpected error: not enough values to unpack (expected 2, got 1)
> Traceback (most recent call last):
>   File "/home/ubuntu/resources/AntiFold/antifold/main.py", line 488, in <module>
>     main(args)
>   File "/home/ubuntu/resources/AntiFold/antifold/main.py", line 438, in main
>     pdb_output_dict = sample_pdbs(
>   File "/home/ubuntu/resources/AntiFold/antifold/main.py", line 227, in sample_pdbs
>     fasta_dict = sample_from_df_logits(
>   File "/home/ubuntu/resources/miniconda3/envs/antifold_cpu/lib/python3.10/site-packages/antifold/antiscripts.py", line 663, in sample_from_df_logits
>     H_orig, L_orig = get_df_seqs_HL(df_logits)
>   File "/home/ubuntu/resources/miniconda3/envs/antifold_cpu/lib/python3.10/site-packages/antifold/antiscripts.py", line 647, in get_df_seqs_HL
>     df_H, df_L = get_dfs_HL(df)
>   File "/home/ubuntu/resources/miniconda3/envs/antifold_cpu/lib/python3.10/site-packages/antifold/antiscripts.py", line 631, in get_dfs_HL
>     Hchain, Lchain = df["pdb_chain"].unique()[:2] # Assume heavy, light
> ValueError: not enough values to unpack (expected 2, got 1)
> 

Interestingly, for another complex with an antigen and nanobody chain the following code gives the same error:
`python antifold/main.py --pdb_file /path/to/PDB.pdb --nanobody_chain H --num_seq_per_target 10`
While if I add the antigen chain, it runs without an error.
`python antifold/main.py --pdb_file /path/to/PDB.pdb --nanobody_chain H --antigen_chain A --num_seq_per_target 10`

Based on the error message, it makes me wonder whether the Ag and VHH chains are interpreted correctly, or by accident as H/L chains in the second command.

**Comment by jdekanter** [comment]
Thank you for the quick reply. That makes a lot of sense, I will look into that!
