### ISSUE TITLE
results (fasta output) using Antifold  and ESM-IF1weights are identifcal

### ISSUE THREAD

**Issue by gabrieliacc** [oxpig/AntiFold#12]
Hi!
Thank you for letting the code available, Antifold is very helpful and fast.

I run my first tests on a antigen-antibody complex and I noted the fasta output is identical for both antifold or esm-if1 weights. Is it expected? Do you have any suggestion?

I run the next command line:

python ~/AntiFold/antifold/main.py --pdb_file ../../../imgt.pdb --heavy_chain H --light_chain L --num_seq_per_target 10 --antigen_chain C --esm_if1_mode --sampling_temp '0.20' --regions "CDR3"

Thanks in advance

Gabriel

**Comment by Magnushhoie** [comment]
Hi Gabriel,

If you look at the outputted probability CSVs instead of just the sampled FASTA sequences, the difference in probability distributions will be clearer.

AntiFold is fine-tuned from the ESM-IF1 weights, so there is certainly some expected overlap in their probability distributions.

At a sampling temperature of 0.20, it may be that primarily the top predicted residue is chosen for both models, and those happen to be the same in your specific case.

**Comment by gabrieliacc** [comment]
Hi Magnus,

I did compared the probability distributions, they differ in the fourth decimal digit. I just wrote because I thought that the differences would be larger when using esm-ef1 weights.

Thank you

Best regards

Gabriel

**Comment by Magnushhoie** [comment]
Hi Gabriel, I'm terribly sorry but it seems like I've forgotten to propagate the model_path parameter to the load_model function. One hint is that the large ESM-IF1 model weights are never actually downloaded, thus they cannot be run. 

I have correct this now, and added a test and example output that shows the difference between the models:

 Test: https://github.com/oxpig/AntiFold/blob/master/testing/antifold_vs_esmif1.sh
Output AntiFold: https://github.com/oxpig/AntiFold/blob/master/output/antifold/6y1l_imgt_HL.csv
Output ESM-IF1: https://github.com/oxpig/AntiFold/blob/master/output/esmif1/6y1l_imgt_HL.csv

There is certainly overlap in the top predicted residues, but definitely not to the point of only differing in the fourth decimal digit.

Thanks for the bug report :)

**Comment by gabrieliacc** [comment]
Hi Magnus,

No problem at all, now I could run the code using both antifold and esm-ef1 weights. It worked, now I had different results for both fasta and csv files!

Thanks for your help

Best,

Gabriel
