### ISSUE TITLE
Sample sequences for nanobodies?

### ISSUE THREAD

**Issue by hqdream** [oxpig/AntiFold#13]
Thanks for the nice work. When I tried to sample sequences for a nanobody, an error occurred that said both heavy chain and light chain must be defined. However, there is no light chain in nanobodies. I am wondering if there was something wrong with my code or antifold currently does not support sampling sequences for nanobodies. 

The code I used is "python antifold/main.py --pdb_file input/example.pdb --nanobody_chain F --num_seq_per_target 10 --sampling_temp "0.2" --regions "CDR1 CDR2 CDR3" ".

The error information was as follows:
[2024-11-01 11:05:15,474] Prediction encountered an unexpected error: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/home/af2/AntiFold/antifold/main.py", line 488, in <module>
    main(args)
  File "/home/af2/AntiFold/antifold/main.py", line 438, in main
    pdb_output_dict = sample_pdbs(
  File "/home/af2/AntiFold/antifold/main.py", line 227, in sample_pdbs
    fasta_dict = sample_from_df_logits(
  File "/home/af2/miniconda3/envs/antifold/lib/python3.10/site-packages/antifold/antiscripts.py", line 663, in sample_from_df_logits
    H_orig, L_orig = get_df_seqs_HL(df_logits)
  File "/home/af2/miniconda3/envs/antifold/lib/python3.10/site-packages/antifold/antiscripts.py", line 647, in get_df_seqs_HL
    df_H, df_L = get_dfs_HL(df)
  File "/home/af2/miniconda3/envs/antifold/lib/python3.10/site-packages/antifold/antiscripts.py", line 631, in get_dfs_HL
    Hchain, Lchain = df["pdb_chain"].unique()[:2] # Assume heavy, light

Thanks a lot.

**Comment by hqdream** [comment]
That‘s great. It's working now. Thanks for your reply. 
I occurred another problem. I generated 1000 sequences using above code. However, I found there were many sequences that were exactly the same in the output fasta file. Is that normal or is there anything wrong? Thanks a lot.
@mhoie

**Comment by mhoie** [comment]
Great! For a given temperature, you can see the exact probabilities for each amino acid in the probabilities CSV file. The default sampling temperature of 0.20 is heavily weighed towards always sampling the most likely residue, and you'll often see variation only in a few hypervariable CDR residues. You can adjust the temperature manually to generate more diversity.

Do note that each sampling is independent, so there are no controls for e.g. filtering out identically generated sequences.

**Comment by Magnushhoie** [comment]
Great! For a given temperature, you can see the exact probabilities for each amino acid in the probabilities CSV file. The default sampling temperature of 0.20 is heavily weighed towards always sampling the most likely residue, and you'll often see variation only in a few hypervariable CDR residues. You can adjust the temperature manually to generate more diversity.

Do note that each sampling is independent, so there are no controls for e.g. filtering out identically generated sequences.
