### ISSUE TITLE
Confused about masking strategy in training..

### ISSUE THREAD

**Issue by tsjain** [oxpig/AntiFold#15]
The paper mentions that 7.5% of the structure is masked using span masking. For a typical antibody, the length of heavy chain and light chain is around 250 amino acids. 7.5% of this would be around 19 positions. But the paper also states that the max length for a span mask is 30 positions.

Can you clarify the apparent discrepancy?

**Comment by Magnushhoie** [comment]
Hi tsjain, I'll refer you to the Supplementary Methods Masking section for details on the sampling strategy here, which is itself based on the mask sampling strategy in the ESM-IF1 [pre-print](https://www.biorxiv.org/content/10.1101/2022.04.10.487779v1).

<img width="505" alt="image" src="https://github.com/user-attachments/assets/63a9250b-a34e-4a20-857f-6a2912ff09aa" />
