### ISSUE TITLE
Could you confirm that the model evolves antigen in training and inference?  

### ISSUE THREAD

**Issue by bzhousd** [oxpig/AntiFold#2]
Dear Authors，  

Congratulations on your brilliant works.   your work is important to my current project.  I am working on predicting sequence given by antibody + antigen complex strucutre.    I have ~200 in-house antibodies,  I tested them using abmpnn and antifold.

The recovery rates of CDR  are 0.67 and 0.69 seperately,  antifold is the winner.  That is great. however,  I have a question about antigen in the model.

When you train the model, did you use antibody alone or antibody + antigen?   In my test,  the prediction result almost are identical if I provide antibody structure or antibody + antigen.    I also found --antibody-chain option in your code,  and I didn't find any effect of this option.  could you provide a command line to show how to evolve antigen?

Thanks

**Comment by Magnushhoie** [comment]
Hi bzhousd, thanks for the kind words!

The model is trained on antibody variable domains only (i.e. without antigens). However, providing an antigen will change AntiFold predictions (primarily in the AbAg interface region - see our [arXiv pre-print](https://arxiv.org/abs/2405.03370)).

```bash
# Run AntiFold on an antibody-antigen complex (enables custom_chain_mode)
python antifold/main.py \
    --out_dir output/antibody_antigen \
    --pdb_file data/antibody_antigen/3hfm.pdb \
    --heavy_chain H \
    --light_chain L \
    --antigen_chain Y
```

Extra chains are only considered when `--custom_chain_mode` is set, however this should have been automatically set when `--antibody_chain` is used. I've fixed this now.

See here for example output:
Antibody only: [https://github.com/oxpig/AntiFold/blob/master/output/antibody_antigen/3hfm_HL.csv](https://github.com/oxpig/AntiFold/blob/master/output/antibody_antigen/3hfm_HL.csv)
Antibody-antigen: [https://github.com/oxpig/AntiFold/blob/master/output/antibody_antigen/3hfm_HLY.csv](https://github.com/oxpig/AntiFold/blob/master/output/antibody_antigen/3hfm_HLY.csv)
