### ISSUE TITLE
The Difficulties of Data Preprocessing

### ISSUE THREAD

**Issue by code4luck** [oxpig/AntiFold#4]
Hello, the paper mentioned using the OAS and SAbDab datasets. Could you please share any related code or notebooks on data preprocessing and partitioning? Thanks.

**Comment by Magnushhoie** [comment]
Hi code4luck, you can find the train/validation/test splits we and AbMPNN uses here, as linked in the paper:
https://zenodo.org/records/8164693/files/oas_splits.csv

PDB files are directly loaded and processed by our dataloader:
https://github.com/oxpig/AntiFold/blob/029aac9890bdaced40fc1dfb981950e043721962/antifold/if1_dataset.py#L21

**Comment by code4luck** [comment]
thanks
