### ISSUE TITLE
Documentation: Unclear how to take advantage of antigen information

### ISSUE THREAD

**Issue by wjs20** [oxpig/AntiFold#9]
In the AntiFold paper, you say that including antigen information can improve the generation quality when generating for antibody-antigen complexes. Its not clear how I can explicitly include this antigen information while sampling sequences. Could you provide more documentation on this?

**Comment by Magnushhoie** [comment]
Hi wjs20, this should work now. Try this example:

```bash
python antifold/main.py \                     
    --pdb_file data/antibody_antigen/3hfm.pdb \
    --heavy_chain H \
    --light_chain L \
    --antigen_chain Y \
    --num_seq_per_target 2 \
    --sampling_temp "0.2" \
    --regions "CDR3"
```

You can also specify any other chains to include with the --pdbs_csv flag and a CSV file.
